### PR TITLE
Update to `v1.0.5`

### PR DESCRIPTION
**Pull request by sugatoray**
- updated version and sha256
- set build.number = 0
- updated abouts section

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged) `NA`
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sugatoray** [comment]
@conda-forge-admin, please rerender

**Review by asford — APPROVED** [review]
LGTM, let's get a clean rerun with the updated idl before firing

**Comment by sugatoray** [comment]
I tested this one with latest `flyteidl` and `grpcio-status` as concurrent recipes in `unionml` PR (https://github.com/conda-forge/staged-recipes/pull/19349).

- PR for `grpcio-status` was merged just now: https://github.com/conda-forge/grpcio-status-feedstock/pull/7

**Review by asford — CHANGES_REQUESTED** [review]
Actually, just spot checked again while looking at #10.

This recipe no longer matches the requirements specified in the upstream pypi.
For example, here the recipe specified `six` which is no longer required by flytekit.

Can you please re-evaluate the requirements, tests, and entrypoints for this recipe working from a grayskull build?

Eg:
```
{% set name = "flytekit" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<37]
  entry_points:
    - pyflyte-execute=flytekit.bin.entrypoint:execute_task_cmd
    - pyflyte-fast-execute=flytekit.bin.entrypoint:fast_execute_task_cmd
    - pyflyte-map-execute=flytekit.bin.entrypoint:map_execute_task_cmd
    - pyflyte=flytekit.clis.sdk_in_container.pyflyte:main
    - flyte-cli=flytekit.clis.flyte_cli.main:_flyte_cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekit-{{ version }}.tar.gz
  sha256: 9f8f5b6af227049b2f7d43722ca33608b059972dcf32ee2681c6482c32d467f5

requirements:
  host:
    - pip
    - python
  run:
    - click >=6.6,<9.0
    - cloudpickle >=2.0.0
    - cookiecutter >=1.7.3
    - croniter >=0.3.20,<4.0.0
    - dataclasses-json >=0.5.2
    - deprecated >=1.0,<2.0
    - diskcache >=5.2.1
    - docker-py >=5.0.3,<6.0.0
    - docker-image-py >=0.1.10
    - docstring_parser >=0.9.0
    - flyteidl >=1.1.3,<1.2.0
    - grpcio >=1.43.0,!=1.45.0,<2.0
    - grpcio-status >=1.43,!=1.45.0
    - keyring >=18.0.1
    - marshmallow-jsonschema >=0.12.0
    - natsort >=7.0.1
    - numpy <1.22.0  # [py<38]
    - pandas >=1.0.0,<2.0.0
    - protobuf >=3.6.1,<4
    - pyarrow >=4.0.0,<7.0.0
    - pyopenssl
    - python
    - python-dateutil >=2.1
    - python-json-logger >=2.0.0
    - pytimeparse >=1.1.8,<2.0.0
    - pytz
    - pyyaml
    - requests >=2.18.4,<3.0.0
    - responses >=0.10.7
    - retry ==0.9.2
    - singledispatchmethod  # [py<38]
    - sortedcontainers >=1.5.9,<3.0.0
    - statsd >=3.0.0,<4.0.0
    - typing-extensions
    - urllib3 >=1.22,<2.0.0
    - wheel >=0.30.0,<1.0.0
    - wrapt >=1.0.0,<2.0.0

test:
  imports:
    - flytekit
    - plugins
  commands:
    - pip check
    - pyflyte-execute --help
    - pyflyte-fast-execute --help
    - pyflyte-map-execute --help
    - pyflyte --help
    - flyte-cli --help
  requires:
    - pip

about:
  home: https://github.com/flyteorg/flytekit
  summary: Flyte SDK for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chevtek
```

**Comment by sugatoray** [comment]
Please see this diff (I had run the grayskull utility). On your left you have the grayskull output for `v1.0.5` and on the right you have what was in `v0.26.1`.

**Comment by asford** [comment]
> Please see this diff (I had run the grayskull utility). On your left you have the grayskull output for `v1.0.5` and on the right you have the dependencies from `v0.26.1`.
> 
> 👉 https://www.diffchecker.com/I3SPcx1b

Yes, it appears that the deps have changed and that the current deps listed are inaccurate. 

Can you please update the requirements listed in meta.yaml to match the upstream requirements from the grayskull run? This should also address the dep warnings above.

**Comment by sugatoray** [comment]
## Reason for Build Failure: `1/N`

[(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=525465&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1063)

```sh
+ pip check
flytekit 1.0.5 requires grpcio-status, which is not installed.
Tests failed for flytekit-1.0.5-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for flytekit-1.0.5-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: flytekit-1.0.5-pyhd8ed1ab_0.tar.bz2
```

**Comment by sugatoray** [comment]
Hi @asford,

I have made the changes. Please take a look at it and let me know, if there's any questions.

**Comment by sugatoray** [comment]
A gentle ping. I have tested/validated the requirements with the grayskull output. I believe the PR is ready now. Please have a look at it and let me know if you have any concerns.

:point_right: Once this is merged, it will help me add `unionml` library on conda-forge.

- https://github.com/conda-forge/staged-recipes/pull/19349

cc: @asford

**Review by asford — APPROVED** [review]
Nice. Thanks for the extra effort here.

**Pull request merged**
