### PR TITLE
flytekit 1.4.1

### PR DESCRIPTION
**Pull request by eapolinario**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by eapolinario** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
LGTM! 🎉

**Review by sugatoray — APPROVED** [review]

**Comment by eapolinario** [comment]
@sugatoray , I was added to the codeowners file in https://github.com/conda-forge/flytekit-feedstock/pull/40 but it looks like I don't have write permissions to the repo. Github validates that file and is now [complaining](https://github.com/conda-forge/flytekit-feedstock/blob/main/.github/CODEOWNERS) about this.

**Comment by sugatoray** [comment]
@eapolinario Interesting! Perhaps it will be fixed after the new build passes post PR merging.

**Pull request merged**
